### ISSUE TITLE
Panic when trying to ask for the connections between two chains

### ISSUE THREAD

**Issue by RaulBernal** [informalsystems/hermes#3380]
## Summary of Bug
Panic when trying to ask for the connections between two chains

## Version
Hermes v1.4.1+45b5c29

## Steps to Reproduce
```
./hermes query connections  --counterparty-chain cosmoshub-4 --chain bitcanna-1
2023-05-30T10:40:20.515009Z  INFO ThreadId(01) using default configuration from '/home/raul/.hermes/config.toml'
2023-05-30T10:40:20.515134Z  INFO ThreadId(01) running Hermes v1.4.1+45b5c29
thread 'main' panicked at 'removal index (is 36) should be < len (is 35)', crates/relayer-cli/src/commands/query/connections.rs:73:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Acceptance Criteria

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate milestone (priority) applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by romac** [comment]
### Detailed reproduction steps

First of all, create 3 connections between ibc-0 and ibc-1:

```shell
$ hermes create connection --a-chain ibc-0 --b-chain ibc-1
$ hermes create connection --a-chain ibc-0 --b-chain ibc-1
$ hermes create connection --a-chain ibc-0 --b-chain ibc-1
```

These connections are identified on ibc-0 as `connection-0`, `connection-1` and `connection-2`.

Then create 3 connections between ibc-0 and ibc-2:

```shell
$ hermes create connection --a-chain ibc-0 --b-chain ibc-2
$ hermes create connection --a-chain ibc-0 --b-chain ibc-2
$ hermes create connection --a-chain ibc-0 --b-chain ibc-2
```

These connections are identified on ibc-0 as `connection-3`, `connection-4` and `connection-5`.

Then, query all the connections on ibc-1:

```shell
$ hermes query connections --chain-id ibc-0
SUCCESS [
    ConnectionId(
        "connection-0",
    ),
    ConnectionId(
        "connection-1",
    ),
    ConnectionId(
        "connection-2",
    ),
    ConnectionId(
        "connection-3",
    ),
    ConnectionId(
        "connection-4",
    ),
    ConnectionId(
        "connection-5",
    ),
]
```

Then filter the connections to only include the ones who point to ibc-1:

```shell
❯ hermes query connections --chain ibc-0 --counterparty-chain ibc-1                                                                                            50% at 14:24:36
thread 'main' panicked at 'removal index (is 5) should be < len (is 4)', crates/relayer-cli/src/commands/query/connections.rs:73:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Let's do the same for the connections pointing to ibc-2:

```shell
$ hermes query connections --chain ibc-0 --counterparty-chain ibc-2
SUCCESS [
    ConnectionId(
        "connection-1",
    ),
    ConnectionId(
        "connection-3",
    ),
    ConnectionId(
        "connection-5",
    ),
]
```

While this does not crash like the command above, we see that the results are wrong.
